# Use root/example user/password credentials
version: '3.1'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8001:80
    volumes:
      - ./TP4/project/api:/var/www/html

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: user1
      MYSQL_PASSWORD: pass
    volumes:
      - mysql-data:/var/lib/mysql
      - ./api:/var/www

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
  
  composer:
    image: composer
    command : install
    volumes:
        - ./api:/var/www
    working_dir: /var/www

      
volumes:
  mysql-data: