FROM php:7.4-apache
RUN docker-php-ext-install mysqli


WORKDIR /usr/src/myapp/
#CMD ["/bin/bash", "tree"]
#ENTRYPOINT ["php", "/usr/src/myapp/docker/docker.php"]

#ENTRYPOINT ["php", "./docker/docker.php"]